### ISSUE TITLE
Compilation fails after updating to ESPHome 2025.8.0

### ISSUE THREAD

**Issue by lifeexplore** [aronsky/esphome-components#43]
After I upgraded to 2025.8.0. It could not be complicated correctly. Log is as blow.

|-- noise-c @ 0.1.10
Compiling .pioenvs/esp32l/src/esphome/components/ble_adv_controller/ble_adv_controller.cpp.o
Compiling .pioenvs/esp32l/src/esphome/components/ble_adv_controller/ble_adv_handler.cpp.o
Compiling .pioenvs/esp32l/src/esphome/components/ble_client/automation.cpp.o
Compiling .pioenvs/esp32l/src/esphome/components/ble_client/ble_client.cpp.o
Compiling .pioenvs/esp32l/src/esphome/components/ble_client/text_sensor/ble_text_sensor.cpp.o
src/esphome/components/ble_adv_controller/ble_adv_controller.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvController::setup()':
src/esphome/components/ble_adv_controller/ble_adv_controller.cpp:65:3: error: 'register_service' was not declared in this scope
   65 |   register_service(&BleAdvController::on_pair, "pair_" + this->get_object_id());
      |   ^~~~~~~~~~~~~~~~
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvHandler::setup()':
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp:155:3: error: 'register_service' was not declared in this scope
  155 |   register_service(&BleAdvHandler::on_raw_decode, "raw_decode", {"raw"});
      |   ^~~~~~~~~~~~~~~~
*** [.pioenvs/esp32l/src/esphome/components/ble_adv_controller/ble_adv_controller.cpp.o] Error 1
*** [.pioenvs/esp32l/src/esphome/components/ble_adv_controller/ble_adv_handler.cpp.o] Error 1
========================= [FAILED] Took 299.03 seconds =========================

**Comment by djrm05** [comment]
yep, same here. Compilation fails for both arduino and esp-idf

**Comment by lazybabyz** [comment]
ESPHome 2025.7.5 esp-idf work~

**Comment by nos486** [comment]
Me too. compilation failed

src/esphome/components/ble_adv_controller/ble_adv_controller.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvController::setup()':
src/esphome/components/ble_adv_controller/ble_adv_controller.cpp:65:3: error: 'register_service' was not declared in this scope
   65 |   register_service(&BleAdvController::on_pair, "pair_" + this->get_object_id());
      |   ^~~~~~~~~~~~~~~~
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp: In member function 'virtual void esphome::bleadvcontroller::BleAdvHandler::setup()':
src/esphome/components/ble_adv_controller/ble_adv_handler.cpp:155:3: error: 'register_service' was not declared in this scope
  155 |   register_service(&BleAdvHandler::on_raw_decode, "raw_decode", {"raw"});
      |   ^~~~~~~~~~~~~~~~
*** [.pioenvs/home/src/esphome/components/ble_adv_controller/ble_adv_controller.cpp.o] Error 1
*** [.pioenvs/home/src/esphome/components/ble_adv_controller/ble_adv_handler.cpp.o] Error 1

**Comment by djrm05** [comment]
Ensure you have this added to your config:
api:
  custom_services: True

Cleanup your build files and try again

With the above I got it working

**Comment by lifeexplore** [comment]
Thank you very much! 
After I added api with 'custom_services: True'. It works!
